# Generated by Django 2.2.4 on 2020-12-18 15:16

from django.db import migrations

def set_field_new_building_in_floor(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    for flat in Flats.objects.all():
        if flat.new_building is None:
            flat.new_building = (flat.construction_year >= 2015)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_field_new_building_in_floor),
    ]


