# Generated by Django 2.2.4 on 2020-12-20 15:44

from django.db import migrations


def clear_field_new_building_in_floor(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    for flat in Flats.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20201219_1406'),
    ]

    operations = [
        migrations.RunPython(clear_field_new_building_in_floor),
    ]
