# Generated by Django 2.2.4 on 2020-12-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
