# Generated by Django 2.2.4 on 2020-12-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_owner_flats'),
        ('property', '0015_delete_owner'),
    ]

    operations = [
    ]
