# Generated by Django 2.2.4 on 2020-12-20 19:15

from django.db import migrations


def set_all_owner(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    for flat in Flats.objects.all():
        Owners.objects.get_or_create(fio=flat.owner, phonenumber=flat.owners_phonenumber,
                                     pure_phone=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_owner'),
    ]

    operations = [
        migrations.RunPython(set_all_owner ),
    ]
