# Generated by Django 2.2.4 on 2020-12-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20201220_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='own_flat',
            field=models.ManyToManyField(blank=True, related_name='owner_flat', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
