# Generated by Django 2.2.4 on 2020-12-21 19:25

from django.db import migrations

def set_field_own_flat_in_owner(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    for flat in Flats.objects.all():
        current_owner = flat.owner
        all_own = Owners.objects.filter(owner_deprecated=current_owner)
        for current_owner in all_own:
            current_owner.own_flat.add(flat)
            current_owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20201220_2312'),
    ]

    operations = [
        migrations.RunPython(set_field_own_flat_in_owner ),
    ]
